### ISSUE TITLE
DRT Revisions & User Testing FY19Q2

### ISSUE THREAD

**Issue by shazadahmed10** [ICPI/DAQ#53]
FY19 Q2 DRT Revisions
--
**Overview**: 
- Leigh and Shazad are preparing the DRT for Q2 data release. 
- New semi annual indicators are being rolled out at this time so giving folks a chance to request new checks if needed. 

**Tasks:**
- [x] Review existing checks
- [x] reviewing & updating DRT info tabs (Nicole) @nmcarloni 
- [x] Consider expansion/inclusion of new indicators (ie TX_ML, OVC)
- [x] reaching out to program POCs for reviewing and adding new checks. Deadline: 2/20 to collect feedback (Kimi, Shaylee, Catherine, Travis, Michelle, etc) (Leigh)
- [x] Action: Divvy up indicators for review, revision, addition  
- [x] DRT template review – (info tabs) 
- [x] Consolidating checks and clarifying outstanding items
- [x] Meeting with systems team (Stephanie) to discuss checks and LOE
- [x] Communicate final proposed checks to systems team (Stephanie)
- [x] Communicate final decisions to DAQ and ICPI

DRT Summary FY19Q2
--
Project Leads: Shazad and Leigh

**Summary:**
- Checks Consolidated through February 27
- Summarized March 1
- Sent to Systems team March 5, 2019
- DRT Checks for FY19Q2 are a more streamlined set of checks than originally proposed.

Project Updates:
---

- Shazad and Stephanie met late last week to review the revised list of requested checks and Shazad began scripting the new checks in the DRT-FlagList master spreadsheet. 
- The checks were then handed over to Leigh to review the  updated the DRT checklist and clarify outstanding questions. 

**Decisions:**
- The annual indicators (HRH and GEND) would be incorporated at a future date since those are not yet pressing, 
- The CXCA, TB, PREP, AGYW, and OVC checks are expected to be added this quarter FY19Q2. 
- This translates into 12 new checks: 
    - 8 logic
    - 2 checks across time
    - 2 site context. 

**Outstanding:**
- There are some outstanding questions regarding reference variables for new indicators. These will be resolved pending follow up from Shazad. 
- Discuss consolidating checks and creating variance bucket (Feasibility, Need, LOE, Timeline).  
- Variance Checks: What does this look like? How would we do this? How do we go about this?
- DRT survey question formulation (#50 ) managed in separate ticket @nmcarloni 
- Gather info on and analyze DRT users from Genie login data (Pooja) #56 - managed in a separte ticket 
- User Feedback Survey (DRT Utility/objectives, timeline, process) #50 

Documents on SharePoint
--
[ICPI > DAQ> DRT > DRT FY19Q2](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FData%20Access%20and%20Quality%20%28DAQ%29%2FData%20Review%20Tool%20%28DRT%29%2FDRT%20FY19%20Q2&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by jb3436** [comment]
FY19Q1 Checks
https://github.com/ICPI/DAQ/issues/51

**Comment by jb3436** [comment]
FY19 Q2 Checks
--

- [ ] **HSS**
1.	Flag if HRH_CURR >= HRH_STAFF. Normal if HRH_CURR < HRH_STAFF. Flag at the site level and PSNU level. Flag message: “HRH_CURR (PEPFAR-supported HRH) should be a subset of HRH_STAFF (total HRH present).”
2.	Flag if HRH_CURR > 0 and sum of all DSD-type indicators = 0. Flag at the site level and PSNU level. Flag message: “Sites with PEPFAR HRH support should be reporting program results in the ‘DSD’ category.”
3.	Flag if HRH_CURR > 0 and site type is NOT scale-up (at the site level). Flag message: “Do not expect PEPFAR support of HRH in non-scale-up sites.” [Note: need to standardize definition of scale-up vs. non-scaleup over fiscal years]
4.	Flag if the rolled up HRH_CURR (CadreCategory/Financial Support) > 0 and PSNU type is NOT scale-up (at the PSNU level)
Do not count HRH_CURR (CadreOU/Financial Support) in this flag. Flag message: “Do not expect PEPFAR support of HRH in non-scale-up districts.” [Note: need to standardize definition of scale-up vs. non-scaleup over fiscal years]

- [ ] **Cervical Cancer**
CXCA_SCRN 
numerator < sum of TX_CURR, Female, 15+ results 
denominator = TX_CURR, Female, 15+ results (numerator)
CXCA_SCRN_POS (calculated indicator)
numerator = CXCA_TX denominator
CXCA_SCRN_POS = CXCA_SCRN (disagg Age/Sex/HIVStatus/ScreenResult/ScreenVisitType) postive + suspected cancer - According to MER guidance, this should be the case, however currently it is only pulling in CXCA_SCRN (screen result) positives. Working with Stephanie O'Hara on these changes for Q2 and awaiting input from SMEs regarding this clarification.
CXCA_TX
denominator = CXCA_SCRN_POS numerator
numerator < CXCA_SCRN numerator AND <=100% of CXCA_SCRN_POS 

- [ ] **Prevention**

Type of Data Quality   Check | Name of Check | Meaning of Check | Program Area | Ref Var1 | Ref Var 2
-- | -- | -- | -- | -- | --
MER Logic Checks |   | Numerator of GEND_GBV ≥ sum of   each individual disaggregate group | Gender | GEND_GBV | GEND_GBV sexual violence +   GEND_GBV physical/emotional violence
MER Logic Checks |   | Total sexual violence numerator   ≥ PEP age/sex disagg for the same reporting period | Gender | GEND_GBV_Sexual Violence (Disagg   of total numerator) | GEND_GBV_N_Sexual Violence_PEP   (disagg)
MER Logic Checks |   | Numerator of PrEP_CURR ≥   PrEP_NEW Numerator for the same reporting period | PrEP | PrEP_CURR (Numerator) | PrEP_NEW (numerator)
MER Logic Checks |   | Numerator of PrEP_CURR ≥   subtotal of required three-month test result disaggregate group. | PrEP | PrEP_CURR (Numerator) | PrEP_NEW three month test result   (disagg)
MER Logic Checks |   | Numerator of PrEP_CURR ≥   subtotal of optional KP disaggregate group. | PrEP | PrEP_CURR (Numerator) | PrEP_NEW KP (disagg)
MER Logic Checks |   | Numerator of AGYW_PREV ≥   denominator | AGYW | AGYW_PREV (numerator) | AGYW_PREV (denominator)
MER Logic Checks |   | Numerator of AGYW_PREV ≥ the   number of AGYW that have completed the DREAMS primary package of   services/interventions | AGYW | AGYW_PREV (numerator) | AGYW_PREV completed primary   package (disagg)


- [ ] **OVC**
![image](https://user-images.githubusercontent.com/13006198/53825003-4ab14100-3f43-11e9-9540-c58ab753400a.png)

- [ ] **TB/TX**


Checks Across Time Periods | FlagT_03, TB_STAT_D:    Targets reported, but no current period results for TB_STAT_D | Targets were reported for this fiscal year by the IM at this   site, but there were no results reported in this quarter.   "Reported" means there was a value (which could include 0) entered   for the IM at this site. | TB | TB_STAT_D | TB_STAT_D_TARGET
-- | -- | -- | -- | -- | --
Checks Across Time Periods | FlagT_04, TB_STAT_D:    current period results reported, but no targets reported for TB_STAT_D | Results were reported in this quarter, but the IM has no targets   for the site for this fiscal year. "Reported" means there was a   value (which could include 0) entered for an IM. | TB | TB_STAT_D | TB_STAT_D_TARGET


Contextual Site   Information | SiteInfo_04, TB_STAT_D.:  Site/IM has targets reported for TB_STAT_D   in this fiscal year | The "Contextual Site   Info" category shows the number of sites (or IM/site combinations,   depending on how the slicers are toggled) that reported targets for this   indicator in the current period. It is included as contextual information to   make it easier to interpret the prevalence/commonness of flags in this tool. | TB | TB_STAT_D_TARGET |  
-- | -- | -- | -- | -- | --
Contextual Site   Information | SiteInfo_05, TB_STAT_D:  Site/IM has results reported for TB_STAT_D | The "Contextual Site   Info" category shows the number of sites (or IM/site combinations,   depending on how the slicers are toggled) that reported results for this   indicator in the current period. It is included as contextual information to   make it easier to interpret the prevalence/commonness of flags in this tool. | TB | TB_STAT_D |  
Contextual Site   Information | SiteInfo_06, TB_STAT_D:  Site/IM has results and targets reported   for TB_STAT_D | The "Contextual Site   Info" category shows the number of sites (or IM/site combinations,   depending on how the slicers are toggled) that reported results and targets   for this indicator in the current period. It is included as contextual   information to make it easier to interpret the prevalence/commonness of flags   in this tool. | TB | TB_STAT_D | TB_STAT_N_TADGET

**Comment by jb3436** [comment]
DRT Summary FY19Q2
--
Project Leads: Shazad and Leigh

**Summary:**
•	Checks Consolidated through February 27
•	Summarized March 1
•	Sent to Systems team March 5, 2019
DRT Checks for FY19Q2 are a more streamlined set of checks than originally proposed.

Project Updates:
---

- Shazad and Stephanie met late last week to review the revised list of requested checks and Shazad began scripting the new checks in the DRT-FlagList master spreadsheet. 
- The checks were then handed over to Leigh to review the  updated the DRT checklist and clarify outstanding questions. 

**Decisions:**
- The annual indicators (HRH and GEND) would be incorporated at a future date since those are not yet pressing, 
- The CXCA, TB, PREP, AGYW, and OVC checks are expected to be added this quarter FY19Q2. 
- This translates into 12 new checks: 
    - 8 logic
    - 2 checks across time
    - 2 site context. 

**Outstanding:**
There are some outstanding questions regarding reference variables for new indicators. These will be resolved pending follow up from Shazad. 

Documents on SharePoint
--
[ICPI > DAQ> DRT > DRT FY19Q2](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FData%20Access%20and%20Quality%20%28DAQ%29%2FData%20Review%20Tool%20%28DRT%29%2FDRT%20FY19%20Q2&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by jb3436** [comment]
FYI @jaliasd @jaliasd @pvinayak001

**Comment by jb3436** [comment]
From Stephanie 3/6

**Next Steps:**
1.	We do need to take an action to update the template as well. I have attached the latest 
DRT_Template.xlsx”. Does anyone on your team have time to make the updates to the “Quick Start Guie” tab and the “Full List of Checks” tab?  
2.	I will start writing the code for the new checks, making updates and do unit testing roughly March 11-20th. However, I will need to stop from March 25-29th for the next Panorama/MSD release. 
3.	Tentatively if Leigh, Shazad and any others available can offer assistance in testing the DRT updates, we will get them set up in our development version of PEPFAR Genie from April ~3rd-5th and a little the week of April 10th for the testing. Please let me know if that sounds do-able. You wouldn’t have to be available for all of that time, just a morning or afternoon would do.
4.	The updates to the DRT will deploy with the open of Genie Production (in DATIM.org) for FY2019 Q2 data the weekend of April 13-14. We will notify users on Monday, April 15th.

I dropped both of these spreadsheets as-is into the ICPI>DAQ>Data Review Tool SharePoint location:
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/Data%20Access%20and%20Quality%20(DAQ)/Data%20Review%20Tool%20(DRT)/Working%20documents/Code%20for%20DRT%20(SQL%2C%20Code%20Builder%2C%20VBA)

**Comment by shazadahmed10** [comment]
Update, 4/11:

User testing done on 4/9 by DAQ members.
Feedback sent to Stephanie. 
DRT template and FlagList_all docs were updated to reflect errors found.
Most errors were around the flag label for TB checks, TX_TB FlagB_1-3 & 5-7 and  TB_PREV B_1

Links to [template](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/Data%20Access%20and%20Quality%20(DAQ)/Data%20Review%20Tool%20(DRT)/Working%20documents/Code%20for%20DRT%20(SQL%2C%20Code%20Builder%2C%20VBA)/DRT_Template_4.11.19.xlsx) and [FlagList_all](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/Data%20Access%20and%20Quality%20(DAQ)/Data%20Review%20Tool%20(DRT)/Working%20documents/Code%20for%20DRT%20(SQL%2C%20Code%20Builder%2C%20VBA)/DRT_FlagList_All_20190411_v1.xlsx) on SP
